server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/WalkerDogW/springcloud_config.git
          #读取目录
          search-paths:
            - springcloud_config
      #分支,默认是master分支
      label: master
  #rabbitmq
  rabbitmq:
    host: 192.168.209.129
    port: 5672
    username: guest
    password: guest


#eureka
eureka:
  client:
    #是否在eureka注册
    register-with-eureka: true
    #检索已在eureka注册的服务，单点无所谓，集群必须开启才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #eureka服务地址
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
  instance:
    #隐藏主机名，改为指定名称
    instance-id: config-center4433
    #访问路径显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，默认是30秒
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，默认90秒，超时将剔除服务
    lease-expiration-duration-in-seconds: 2




#暴露监控端口
management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"