server:
  port: 80

spring:
  application:
    name: nacos-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://47.100.136.208:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: cloud
    password: cloud

    druid:
      test-while-idle: true
      validation-query: select 1
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.117.128:8848

    sentinel:
      transport:
        dashboard: 192.168.117.128:8858
        port: 8719


service-url:
  nacos-user-service: http://nacos-payment-service


mybatis:
  mapperLocations: classpath:mapper/*.xml




management:
  endpoints:
    web:
      exposure:
        include: '*'
