server:
  port: 82

spring:
  application:
    name: cloud-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://47.100.136.208:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: cloud
    password: cloud
    druid:
      test-while-idle: true
      validation-query: select 1

  cloud:
    #注册到consul的地址
    consul:
      host: 192.168.209.129
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        #本机检测链接
        health-check-url: http://192.168.76.1:8005/actuator/health
#    zookeeper:
#      #注册到zookeeper的地址
#      connect-string: 192.168.209.129:2181


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: site.jaavee.cloud_api_commons.entities    # 所有Entity别名类所在包





#eureka:
#  client:
#    #是否在eureka注册
#    register-with-eureka: true
#    #检索已在eureka注册的服务，单点无所谓，集群必须开启才能配合ribbon使用负载均衡
#    fetch-registry: true
#    service-url:
#      #eureka服务地址
#      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
#  instance:
#    #隐藏主机名，改为指定名称
#    instance-id: order80
#    #访问路径显示IP地址
#    prefer-ip-address: true