server:
  port: 8401

spring:
  application:
    name: sentinel-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://47.100.136.208:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: cloud
    password: cloud

    druid:
      test-while-idle: true
      validation-query: select 1

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.117.128:8848
    sentinel:
      transport:
        dashboard: 192.168.117.128:8858
        port: 8719
      eager: true
      #https://github.com/alibaba/Sentinel/wiki/如何使用#规则的种类
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.117.128:8848
            dataId: sentinel-service #nacos配置名
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow









mybatis:
  mapperLocations: classpath:mapper/*.xml




management:
  endpoints:
    web:
      exposure:
        include: '*'
